Project contrans_database {
  database_type: 'PostgreSQL'
  Note: '''
    # Congress transparency database
    ### Version 0.0.1
    The data comes from voteview.org and Propublica's Congress API.
  '''
}
Table rollcalls as R {
    chamber varchar [pk]
    rollnumber int [pk]
    congress int
    date date
    session int
    clerk_rollnumber int
    yea_count int
    nay_count int
    nominate_mid_1 float
    nominate_mid_2 float
    nominate_spread_1 float
    nominate_spread_2 float
    nominate_log_likelihood float
    bill_number varchar
    vote_result varchar
    vote_desc varchar
    vote_question varchar
    dtl_desc varchar
    note: "Data about individual members of Congress"
}
Table members as M {
    propublica_id varchar [pk]
    title varchar
    short_title varchar
    first_name varchar
    middle_name varchar
    last_name varchar
    suffix varchar
    congress float
    chamber varchar
    icpsr float
    state varchar
    district varchar
    at_large varchar
    gender varchar
    party varchar
    date_of_birth date
    leadership_role varchar
    twitter_account varchar
    facebook_account varchar
    youtube_account varchar
    url varchar
    rss_url varchar
    seniority int
    next_election int
    total_votes float
    missed_votes float
    total_present float
    office varchar
    phone varchar
    fax varchar
    missed_votes_pct float
    votes_with_party_pct float
    votes_against_party_pct float
    DWNOMINATE float
    propublica_endpoint varchar
    last_updated datetime
    note: "Data about the topic and result of roll call votes overall"
}
Table member_vote as V {
    rollnumber int [pk]
    icpsr float [pk]
    congress int
    chamber varchar
    cast_code int
    prob float
    note: "Individual members' votes on each roll call"
}

Table charwords as C {
    sponsor_id varchar [pk]
    word varchar [pk]
    tf_idf float
}

Ref: M.icpsr < V.icpsr
Ref: R.rollnumber < V.rollnumber
Ref: R.chamber < V.chamber
Ref: C.sponsor_id > M.propublica_id